In [15]:
import numpy as np

In [16]:
A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

<h2>Array Calculations and Array Indexing</h2> <br><b>1.</b>

In [14]:
print(np.add(A, B))
print(np.multiply(A, B))

[ 6  8 10 12]
[ 5 12 21 32]


<b> 2. </b>

In [25]:
def find_mean(Array):
    return np.sum(Array) / len(Array)
    
print(find_mean(A))
print(np.full(len(A), find_mean(A)))

2.5
[ 2.5  2.5  2.5  2.5]


<b> 3. </b>

In [21]:
print(np.std(A))

1.11803398875


In [23]:
print(sqrt()

1.11803398875


In [37]:
def find_stdev(Array):
    means = np.full(len(Array), find_mean(Array))
    return sqrt(np.sum(np.square(np.subtract(Array, means))) / len(Array))

print(find_stdev(A))
    

1.11803398875
